# Parameters and credentials for the API request.
API_URL = 'http://api.openweathermap.org/data/2.5/weather'
UNITS = 'metric'
APPID = 'API key generated by Openweather'

# A list of city id's to search.
CITIES = [524894, 5128581, 264371, 745042]
# The id's above are here for demonstration purposes!
# You can download a catalogue of cities with their id's in json format from the Openweather site.


# Database parameters and credentials.
DBNAME = 'The name of your database'
HOST = 'The host parameter'
USER = 'Your Postgres username'
PASSWORD = 'Your Postgres password'
TABLESPACE = "Your Postgres tablespace"

# Table names
UNSORTED_W = 'unsorted_weather'
SORTED_W = 'sorted_weather'
